# Generated by Django 6.0.3 on 2026-03-14 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pharmacie', models.CharField(max_length=150, verbose_name='Nom de la pharmacie')),
                ('code_2st', models.CharField(blank=True, max_length=10, verbose_name='Code 2ST')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('nom_responsable', models.CharField(blank=True, max_length=100, verbose_name='Nom du responsable')),
                ('tel_responsable', models.CharField(blank=True, max_length=20, verbose_name='Tél. responsable')),
                ('email_pharmacie', models.EmailField(blank=True, max_length=254, verbose_name='Email pharmacie')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pharmacies/logos/')),
                ('sous_contrat', models.BooleanField(default=False, verbose_name='Sous contrat')),
                ('date_contrat', models.DateField(blank=True, null=True, verbose_name='Date contrat')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('windev_client_id', models.BigIntegerField(blank=True, help_text='IDClient dans T_Client WinDev', null=True, unique=True, verbose_name='IDClient WinDev')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to='zones.commune')),
                ('quartier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to='zones.quartier')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'pharmacie'}, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacie_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['nom_pharmacie'],
            },
        ),
        migrations.CreateModel(
            name='EquipementPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('type_equipement', models.CharField(choices=[('logiciel', 'Logiciel'), ('materiel', 'Matériel'), ('reseau', 'Réseau'), ('autre', 'Autre')], max_length=20, verbose_name='Type')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='N° série')),
                ('date_installation', models.DateField(blank=True, null=True, verbose_name='Date installation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='pharmacies.pharmacie')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ContactPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='pharmacies.pharmacie')),
            ],
            options={
                'verbose_name': 'Contact pharmacie',
                'verbose_name_plural': 'Contacts pharmacie',
            },
        ),
    ]
