# Generated by Django 6.0.3 on 2026-03-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='date_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Date maintenance'),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='interieur_pays',
            field=models.BooleanField(default=False, verbose_name='Intérieur du pays'),
        ),
    ]
