# Generated by Django 6.0.3 on 2026-03-14 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(choices=[('a_distance', 'À distance'), ('sur_site', 'Sur site')], max_length=20, verbose_name="Type d'intervention")),
                ('actions_realisees', models.TextField(verbose_name='Actions réalisées')),
                ('resultat', models.CharField(choices=[('resolu', 'Résolu'), ('partiellement', 'Partiellement résolu'), ('non_resolu', 'Non résolu'), ('en_attente_piece', 'En attente pièce/matériel')], max_length=30, verbose_name='Résultat')),
                ('temps_passe_minutes', models.PositiveIntegerField(default=0, verbose_name='Temps passé (minutes)')),
                ('recommandations', models.TextField(blank=True, verbose_name='Recommandations')),
                ('signature_numerique', models.ImageField(blank=True, null=True, upload_to='interventions/signatures/%Y/%m/', verbose_name='Signature numérique')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('distance_pharmacie_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distance pharmacie (km)')),
                ('geolocation_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Date/heure géolocalisation')),
                ('windev_detail_intervention_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='IDDetailIntervention WinDev')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_intervention', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': "Rapport d'intervention",
                'verbose_name_plural': "Rapports d'intervention",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='interventions/photos/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='interventions.rapportintervention')),
            ],
            options={
                'verbose_name': 'Photo intervention',
                'verbose_name_plural': 'Photos intervention',
            },
        ),
    ]
