# Generated by Django 6.0.3 on 2026-03-14 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Référence')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet du ticket')),
                ('type_intervention', models.CharField(choices=[('en_ligne', '🖥️ Assistance en ligne'), ('sur_site', '🚗 Intervention sur site')], max_length=20, verbose_name="Type d'intervention")),
                ('categorie', models.CharField(choices=[('logiciel', 'Logiciel'), ('materiel', 'Matériel'), ('reseau', 'Réseau'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('urgence', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('critique', 'Critique')], default='moyen', max_length=20, verbose_name="Niveau d'urgence")),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('assigne', 'Assigné'), ('en_cours', 'En cours'), ('en_attente', 'En attente'), ('resolu', 'Résolu'), ('cloture', 'Clôturé')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('windev_intervention_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='IDIntervention WinDev')),
                ('windev_besoin_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='IDBesoinsClient WinDev')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Date assignation')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Date début traitement')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date résolution')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date clôture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'technicien'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='pharmacies.pharmacie', verbose_name='Pharmacie')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tickets/attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='TicketDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(verbose_name='Motif de la délégation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_technicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_from', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='tickets.ticket')),
                ('to_technicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Délégation',
                'verbose_name_plural': 'Délégations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(verbose_name='Note (1-5)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Message')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/messages/%Y/%m/')),
                ('is_internal', models.BooleanField(default=False, help_text='Visible uniquement par les techniciens et admins', verbose_name='Note interne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Ancien statut')),
                ('new_status', models.CharField(max_length=20, verbose_name='Nouveau statut')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Historique statut',
                'verbose_name_plural': 'Historiques statuts',
                'ordering': ['-created_at'],
            },
        ),
    ]
