# Generated by Django 6.0.3 on 2026-03-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('windev_to_web', 'WinDev → Web'), ('web_to_windev', 'Web → WinDev')], max_length=20, verbose_name='Direction')),
                ('entity_type', models.CharField(help_text='Ex: client, intervention, utilisateur', max_length=50, verbose_name="Type d'entité")),
                ('records_synced', models.PositiveIntegerField(default=0, verbose_name='Enregistrements synchronisés')),
                ('records_failed', models.PositiveIntegerField(default=0, verbose_name='Enregistrements échoués')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('partial', 'Partiel'), ('failed', 'Échec')], max_length=20, verbose_name='Statut')),
                ('error_details', models.TextField(blank=True, verbose_name='Détails erreurs')),
                ('started_at', models.DateTimeField(verbose_name='Début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de synchronisation',
                'verbose_name_plural': 'Logs de synchronisation',
                'ordering': ['-created_at'],
            },
        ),
    ]
