# Generated by Django 6.0.3 on 2026-03-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windev_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50, unique=True, verbose_name="Type d'entité")),
                ('direction', models.CharField(max_length=20, verbose_name='Direction')),
                ('last_synced_id', models.BigIntegerField(default=0, verbose_name='Dernier ID synchronisé')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière sync réussie')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curseur de synchronisation',
                'verbose_name_plural': 'Curseurs de synchronisation',
            },
        ),
    ]
