# Generated by Django 6.0.3 on 2026-03-14 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['region__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='zones.commune')),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ['commune__name', 'name'],
                'unique_together': {('name', 'commune')},
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='zones.region'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la zone')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communes', models.ManyToManyField(blank=True, related_name='zones', to='zones.commune')),
                ('quartiers', models.ManyToManyField(blank=True, related_name='zones', to='zones.quartier')),
                ('regions', models.ManyToManyField(blank=True, related_name='zones', to='zones.region')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicienProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competences', models.CharField(choices=[('logiciel', 'Logiciel'), ('materiel', 'Matériel'), ('reseau', 'Réseau'), ('tous', 'Tous')], default='tous', max_length=20, verbose_name='Compétence principale')),
                ('max_tickets_simultanes', models.PositiveIntegerField(default=5, verbose_name='Max tickets simultanés')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('last_location_update', models.DateTimeField(blank=True, null=True, verbose_name='Dernière MAJ position')),
                ('windev_technicien_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID Technicien WinDev')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'technicien'}, on_delete=django.db.models.deletion.CASCADE, related_name='technicien_profile', to=settings.AUTH_USER_MODEL)),
                ('zones', models.ManyToManyField(blank=True, related_name='techniciens', to='zones.zone')),
            ],
            options={
                'verbose_name': 'Profil technicien',
                'verbose_name_plural': 'Profils techniciens',
            },
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together={('name', 'region')},
        ),
    ]
