# Generated by Django 6.0.3 on 2026-03-14 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ticket_created', 'Nouveau ticket'), ('ticket_assigned', 'Ticket assigné'), ('ticket_updated', 'Ticket mis à jour'), ('ticket_resolved', 'Ticket résolu'), ('ticket_delegated', 'Ticket délégué'), ('message_received', 'Nouveau message'), ('account_validated', 'Compte validé'), ('report_submitted', 'Rapport soumis')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('link', models.CharField(blank=True, help_text='URL relative vers la ressource concernée', max_length=500, verbose_name='Lien')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
